; RETO (+15 PUNTOS EXTRA)
;ELABORE UN PROGRAMA QUE SAQUE LA FECHA DEL SISTEMA Y LA HORA DEL 
; SISTEMA PERO INVERTIDO
; EJEMPLO:    07:42:30 HRS  12/03/2015
;        SACA 03:24:70 SRH  5102/30/21   


;SACAR DIFERENTES MENSAJES UNA VEZ QUE APRIETE CUALQUIER TECLA
CHONA MACRO JLO, TAYLOR
    LOCAL AB
    MOV AH, 0EH   
    MOV SI, 0
AB: MOV AL, JLO[SI]
    INT 10H
    INC SI
    CMP AL, TAYLOR
    JNZ AB
CHONA ENDM

ORG 100H 
JMP INICIO
BSB DB 'ENSAMBLADOR ESTA CHIDO!',0
BEYONCE DB 'AHORA SI PODRAN HACER EL RETO DE HOY!',3
SHAKIRA DB 'SOLO FALTAN DOS TEMAS EN ENSAMBLADOR', 7


INICIO: MOV AH, 00 
        MOV AL,03
        INT 10H   ;ABRIR PANTALLA 
        CALL JUANITA
        CHONA BSB,0
        CALL JUANITA
        CHONA BEYONCE,3
        CALL JUANITA
        CHONA SHAKIRA,7
        RET 

JUANITA PROC
    MOV AH, 01
AB: INT 16H
    JZ AB      ;ESPERA HASTA QUE HAYA OPRIMIDO ALGO
    MOV AH, 00 ;LIMPIAR BUFFER
    INT 16H
    RET
JUANITA ENDP                                   