;ELABORE UN PROGRAMA QUE TOME UN ENUNCIADO DESDE EL TECLADO
;Y LO DESPLIEGUE LETRA A LETRA ESPERANDO CINCO SEGUNDOS ENTRE LETRA.
ORG 100H
MOV AH, 00
MOV AL,03
INT 10H   ;ABRIR PANTALLA
;A PARTIR DE AQUI GUARDAR LA INFORMACION
MOV DI, 300H
ENTRADA:  MOV AH, 01
AB:       INT 16H    ;TOMO EL DATO DESDE EL TECLADO
          JZ AB
          STOSB
          MOV AH,00
          INT 16H   ;LIMPIAR EL BUFFER
          CMP AL, 0DH  ;COMPARA CONTRA ENTER
          JNZ ENTRADA
          MOV SI,300H
; SACAR LOS DATOS INGRESADO POR VIDEO
SALIDA:   MOV AH, 0EH
          LODSB 
          INT 10H  ;IMPRIMI EN PANTALLA
          MOV AH, 86H
          MOV CX, 4CH
          MOV DX, 4B40H
          INT 15H   ;ESPERA DE 5 SEGUNDOS
          CMP AL, 0DH
          JNZ SALIDA
          RET                                    